### PR TITLE
Interim Report

### LINKED ISSUE #221: Interim Report

### PR DESCRIPTION
**Pull request by 1Solon**
### Description

Adds the interim report for the project.

Closes #221 

### Type of change

Please select the option that best describes the changes made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

### CODE REVIEW

**Comment by 1Solon** [comment]
Merge conflicts has to be fixed before we merge.

**Comment by 1Solon** [comment]
This PR is irrevocably damaged. Nuclear option it is. Hold one.

**Comment by 1Solon** [comment]
Nuclear option successfully invoked!

note:
#  **do not use a `git pull origin main` unless you **EXPRESSLY** know what it will do** 

* *(this is a reminder to myself more then anything)*
** *(for any git historians, I am so very sorry)*

**Review by JessicaFornetti — APPROVED** [review]

**Review by anaisbl — APPROVED** [review]
Looks great!

**Pull request merged**
